const serviceContexts = {
  TENANT_ACCOUNT_CREATE: 'TENANT_ACCOUNT_CREATE',
  TENANT_ACCOUNT_GET_BY_ID: 'TENANT_ACCOUNT_GET_BY_ID',
  TENANT_ACCOUNT_GET_BY_TENANT_ID: 'TENANT_ACCOUNT_GET_BY_TENANT_ID',
  TENANT_ACCOUNT_GET_BY_ACCOUNT_ID_AND_TENANT_ID:
    'TENANT_ACCOUNT_GET_BY_ACCOUNT_ID_AND_TENANT_ID',
  TENANT_ACCOUNT_GET_BY_USER_DEFINED_IDENTIFICATION:
    'TENANT_ACCOUNT_GET_BY_USER_DEFINED_IDENTIFICATION',
  TENANT_ACCOUNT_DELETE_BY_ID: 'TENANT_ACCOUNT_DELETE_BY_ID',
  TENANT_ACCOUNT_UPDATE_BY_ID: 'TENANT_ACCOUNT_UPDATE_BY_ID',
  TENANT_ACCOUNT_UPDATE_NON_SENSITIVE_PROPERTIES_BY_ID:
    'TENANT_ACCOUNT_UPDATE_NON_SENSITIVE_PROPERTIES_BY_ID',
  TENANT_ACCOUNT_UPDATE_EMAIL_BY_ID: 'TENANT_ACCOUNT_UPDATE_BY_ID',
  TENANT_ACCOUNT_UPDATE_USERNAME_BY_ID: 'TENANT_ACCOUNT_UPDATE_USERNAME_BY_ID',
  TENANT_ACCOUNT_UPDATE_PHONE_BY_ID: 'TENANT_ACCOUNT_UPDATE_PHONE_BY_ID',
  TENANT_ACCOUNT_DISABLE: 'TENANT_ACCOUNT_DISABLE',
  TENANT_ACCOUNT_ENABLE: 'TENANT_ACCOUNT_ENABLE',

  TENANT_CREATE: 'TENANT_CREATE',
  TENANT_GET_BY_ID: 'TENANT_GET_BY_ID',
  TENANT_DELETE_BY_ID: 'TENANT_DELETE_BY_ID',
  TENANT_UPDATE_BY_ID: 'TENANT_UPDATE_BY_ID',
  TENANT_UPDATE_NON_SENSITIVE_PROPERTIES_BY_ID:
    'TENANT_UPDATE_NON_SENSITIVE_PROPERTIES_BY_ID',
  TENANT_SET_CUSTOM_PROPERTY_BY_ID: 'TENANT_SET_CUSTOM_PROPERTY_BY_ID',
  TENANT_GET_CUSTOM_PROPERTY_BY_ID: 'TENANT_DET_CUSTOM_PROPERTY_BY_ID',
  TENANT_DELETE_CUSTOM_PROPERTY_BY_ID: 'TENANT_DELETE_CUSTOM_PROPERTY_BY_ID',

  ENVIRONMENT_CREATE: 'ENVIRONMENT_CREATE',
  ENVIRONMENT_GET_BY_ID: 'ENVIRONMENT_GET_BY_ID',
  ENVIRONMENT_GET_BY_TENANT_ID: 'ENVIRONMENT_GET_BY_TENANT_ID',
  ENVIRONMENT_DELETE_BY_ID: 'ENVIRONMENT_DELETE_BY_ID',
  ENVIRONMENT_UPDATE_BY_ID: 'ENVIRONMENT_UPDATE_BY_ID',
  ENVIRONMENT_UPDATE_NON_SENSITIVE_PROPERTIES_BY_ID:
    'ENVIRONMENT_UPDATE_NON_SENSITIVE_PROPERTIES_BY_ID',
  ENVIRONMENT_SET_CUSTOM_PROPERTY_BY_ID:
    'ENVIRONMENT_SET_CUSTOM_PROPERTY_BY_ID',
  ENVIRONMENT_GET_CUSTOM_PROPERTY_BY_ID:
    'ENVIRONMENT_DET_CUSTOM_PROPERTY_BY_ID',
  ENVIRONMENT_DELETE_CUSTOM_PROPERTY_BY_ID:
    'ENVIRONMENT_DELETE_CUSTOM_PROPERTY_BY_ID',

  ENVIRONMENT_ACCOUNT_CREATE: 'ENVIRONMENT_ACCOUNT_CREATE',
  ENVIRONMENT_ACCOUNT_GET_BY_ID: 'ENVIRONMENT_ACCOUNT_GET_BY_ID',
  ENVIRONMENT_ACCOUNT_DELETE_BY_ID:
    'ENVIRONMENT_ACCOUNT_DELETE_BY_ID',
  ENVIRONMENT_ACCOUNT_UPDATE_BY_ID:
    'ENVIRONMENT_ACCOUNT_UPDATE_BY_ID',
  ENVIRONMENT_ACCOUNT_UPDATE_NON_SENSITIVE_PROPERTIES_BY_ID:
    'ENVIRONMENT_ACCOUNT_UPDATE_NON_SENSITIVE_PROPERTIES_BY_ID',

  ENVIRONMENT_ACCOUNT_UPDATE_EMAIL_BY_ID:
    'ENVIRONMENT_ACCOUNT_UPDATE_BY_ID',
  ENVIRONMENT_ACCOUNT_UPDATE_USERNAME_BY_ID:
    'ENVIRONMENT_ACCOUNT_UPDATE_USERNAME_BY_ID',
  ENVIRONMENT_ACCOUNT_UPDATE_PHONE_BY_ID:
    'ENVIRONMENT_ACCOUNT_UPDATE_PHONE_BY_ID',
  ENVIRONMENT_ACCOUNT_SET_CUSTOM_PROPERTY_BY_ID:
    'ENVIRONMENT_ACCOUNT_SET_CUSTOM_PROPERTY_BY_ID',
  ENVIRONMENT_ACCOUNT_GET_CUSTOM_PROPERTY_BY_ID:
    'ENVIRONMENT_ACCOUNT_DET_CUSTOM_PROPERTY_BY_ID',
  ENVIRONMENT_ACCOUNT_DELETE_CUSTOM_PROPERTY_BY_ID:
    'ENVIRONMENT_ACCOUNT_DELETE_CUSTOM_PROPERTY_BY_ID',
  ENVIRONMENT_ACCOUNT_DISABLE: 'ENVIRONMENT_ACCOUNT_DISABLE',
  ENVIRONMENT_ACCOUNT_ENABLE: 'ENVIRONMENT_ACCOUNT_ENABLE',

  DATABASE_INSTANCE: 'DATABASE_INSTANCE',

  // Session contexts
  SESSION_CREATE: 'SESSION_CREATE',
  SESSION_FIND_BY_TOKEN: 'SESSION_FIND_BY_TOKEN',
  SESSION_FIND_VALID_BY_TOKEN: 'SESSION_FIND_VALID_BY_TOKEN',
  SESSION_UPDATE_LAST_ACTIVE: 'SESSION_UPDATE_LAST_ACTIVE',
  SESSION_DELETE_BY_TOKEN: 'SESSION_DELETE_BY_TOKEN',
  SESSION_DELETE_ALL_BY_ACCOUNT: 'SESSION_DELETE_ALL_BY_ACCOUNT',
  SESSION_FIND_ALL_BY_ACCOUNT: 'SESSION_FIND_ALL_BY_ACCOUNT',
  SESSION_DELETE_EXPIRED: 'SESSION_DELETE_EXPIRED',

  // Auth contexts
  AUTH_HASH_PASSWORD: 'AUTH_HASH_PASSWORD',
  AUTH_SIGNUP: 'AUTH_SIGNUP',
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_FORGOT_PASSWORD: 'AUTH_FORGOT_PASSWORD',
  AUTH_RESET_PASSWORD: 'AUTH_RESET_PASSWORD',

  // Password reset contexts
  PASSWORD_RESET_CREATE: 'PASSWORD_RESET_CREATE',
  PASSWORD_RESET_FIND_BY_TOKEN: 'PASSWORD_RESET_FIND_BY_TOKEN',
  PASSWORD_RESET_MARK_AS_USED: 'PASSWORD_RESET_MARK_AS_USED',
  PASSWORD_RESET_DELETE_BY_ACCOUNT: 'PASSWORD_RESET_DELETE_BY_ACCOUNT',
  PASSWORD_RESET_DELETE_EXPIRED: 'PASSWORD_RESET_DELETE_EXPIRED',
} as const;

const useCaseContexts = {
  CREATE_NEW_TENANT_USE_CASE: 'CREATE_NEW_TENANT_USE_CASE',
} as const;

export const contexts = {
  ...serviceContexts,
  ...useCaseContexts,
};
