export const contexts = {
  ACCOUNT_PROFILE_CREATE: 'ACCOUNT_PROFILE_CREATE',
  GET_ACCOUNT_BY_ID: 'GET_ACCOUNT_BY_ID',
  GET_PROFILE_BY_ACCOUNT_ID: 'GET_PROFILE_BY_ACCOUNT_ID',
  REMOVE_ACCOUNT_BY_ID: 'REMOVE_ACCOUNT_BY_ID',
  UPDATE_ACCOUNT_BY_ID: 'UPDATE_ACCOUNT_BY_ID',
  UPDATE_PROFILE_BY_ACCOUNT_ID: 'UPDATE_PROFILE_BY_ACCOUNT_ID',
  UPDATE_ACCOUNT_UNPROTECTED_FIELDS: 'UPDATE_ACCOUNT_UNPROTECTED_FIELDS',
  PROFILE_RETRIEVE: 'PROFILE_RETRIEVE',
  DATABASE_INSTANCE: 'DATABASE_INSTANCE',
} as const;
