export const contexts = {
  ACCOUNT_CREATE: 'ACCOUNT_CREATE',
  ACCOUNT_GET_BY_ID: 'ACCOUNT_GET_BY_ID',
  ACCOUNT_REMOVE_BY_ID: 'ACCOUNT_REMOVE_BY_ID',
  ACCOUNT_UPDATE_BY_ID: 'ACCOUNT_UPDATE_BY_ID',
  TENANT_CREATE: 'TENANT_CREATE',
  TENANT_GET_BY_ID: 'TENANT_GET_BY_ID',
  TENANT_REMOVE_BY_ID: 'TENANT_REMOVE_BY_ID',
  TENANT_UPDATE_BY_ID: 'TENANT_UPDATE_BY_ID',
  DATABASE_INSTANCE: 'DATABASE_INSTANCE',
} as const;
